# FILE: backend/ai/computer_basics_curriculum.py
# Computer Basics — 30 Day Complete Curriculum
# Structure: concept + how_to + example + task + submit_guide + feedback_prompt

COMPUTER_BASICS_30_DAYS = [
    {
        "day": 1,
        "title": "Computer aur Internet ka Taaruf",
        "concept": "Computer ek machine hai jo tumhare instructions follow karti hai. Internet ek duniya bhar mein phaili wire ka jaal hai. Aaj ke daur mein jo log computer aur internet sahi use karna jaante hain, woh ghar baith ke $500-$2000 per month kama rahe hain.",
        "how_to": "1. chrome.google.com pe jao ya Google Chrome download karo\n2. chatgpt.com kholo\n3. Free account banao\n4. Message box mein type karo: 'Computer aur internet kya hain? Mujhe simple mein samjhao'\n5. Jawab parho\n6. Phir type karo: 'GoHighLevel kya hai aur isse paise kaise kamate hain?'\n7. Jawab parho aur note karo\n8. Type karo: 'Pakistan mein online freelancing se kitna kama sakte hain?'\n9. Type karo: 'Ek beginner digital skills kahan se start kare?'\n10. Sab screenshots lo",
        "example": "Kamran 22 saal ka tha Lahore se. Usay kuch nahi aata tha. ChatGPT pe type kiya 'freelancing kya hoti hai' — ek ghante mein samajh aaya ke Fiverr pe logo design karke paise milte hain. 6 mahine baad $400/month kama raha tha.",
        "task": "ChatGPT kholo aur yeh 3 cheezein search karo:\n1. 'GoHighLevel kya hai aur isse paise kaise kamate hain?'\n2. 'Pakistan mein online freelancing se kitna kama sakte hain?'\n3. 'Ek beginner digital skills kahan se start kare?'\nHar jawab ka screenshot lo. Jo 3 cheezein sabse interesting lagein — note karo.",
        "submit_guide": "Screenshots kaise lo:\n- Windows: Windows key + Shift + S\n- Mac: Command + Shift + 4\n- Mobile: Power + Volume Down\n\nSubmit karo: 3 screenshots — har ChatGPT search ka alag screenshot",
        "success_criteria": "3 ChatGPT searches complete, screenshots clear",
        "points": 30,
        "submission_type": "screenshot",
        "feedback_prompt": "Student ne ChatGPT use kiya. Feedback do: kya acha kiya, ChatGPT better use karne ke 2 tips, aur motivation ke saath batao yeh pehla step hai ek bade safar ka."
    },
    {
        "day": 2,
        "title": "Browser Master — Internet ka Darwaza",
        "concept": "Browser woh program hai jisse tum internet use karte ho. Professional log ek saath 10-15 tabs khol ke kaam karte hain. GHL, Zapier, Make.com — sab browser mein chalte hain.\n\nZaroori shortcuts:\n- Ctrl+T = New tab\n- Ctrl+W = Close tab\n- Ctrl+Tab = Switch tabs\n- Ctrl+D = Bookmark\n- Ctrl+H = History\n- Ctrl+Shift+N = Incognito\n- Ctrl+F = Find on page",
        "how_to": "1. Chrome kholo\n2. Address bar mein google.com type karo\n3. Ctrl+T se naya tab kholo\n4. 5 websites kholo alag tabs mein: gohighlevel.com, zapier.com, fiverr.com, upwork.com, linkedin.com\n5. Ctrl+Tab se tabs switch karo\n6. Har website pe 1-2 minute spend karo — explore karo\n7. GHL website pe kya features mention hain note karo\n8. Ctrl+D se GHL, Fiverr, Upwork bookmark karo\n9. ChatGPT mein type karo: 'GoHighLevel website pe jo features hain unhe explain karo'\n10. Screenshot lo — sab 5 tabs visible hon",
        "example": "Sara virtual assistant hai. Wo ek saath email (tab 1), client website (tab 2), GHL (tab 3), Calendar (tab 4), Slack (tab 5) khol ke kaam karti hai. Tab shortcuts se seconds mein switch karti hai. Client kehta hai 'You're so fast!' — actually sirf browser sahi use karti hai.",
        "task": "1. Chrome mein exactly yeh 5 tabs kholo: gohighlevel.com, zapier.com, fiverr.com, upwork.com, linkedin.com\n2. Har site pe jao aur dekho kya offer karte hain\n3. GHL site pe visit karo aur ChatGPT mein paste karo features — explanation maango\n4. Teeno sites bookmark karo\n5. Screenshot lo jisme sab 5 tabs clearly dikh rahein",
        "submit_guide": "1 screenshot submit karo:\n- Browser mein 5 tabs visible hon\n- Har tab ka naam dikh raha ho\n- Ek website active ho",
        "success_criteria": "5 tabs open, bookmarks created, GHL explored",
        "points": 30,
        "submission_type": "screenshot",
        "feedback_prompt": "Browser use ka feedback do. Advanced Chrome tip share karo (extensions waghera). Batao yeh 5 websites unke career mein kaisi use hongi."
    },
    {
        "day": 3,
        "title": "Google Search — Smart Research Karna Seekho",
        "concept": "Google sirf search engine nahi — yeh ek skill hai. Smart search tricks:\n- 'quotes mein' = exact phrase\n- site:youtube.com = sirf us site mein\n- filetype:pdf = sirf PDFs\n- word1 OR word2 = dono mein se koi\n\nGoogle tools: Search, Images, News, Maps, Translate, Scholar\nFreelancer ke liye Google ek weapon hai.",
        "how_to": "1. google.com kholo\n2. Search: GoHighLevel tutorial for beginners\n3. Search: 'GoHighLevel' pricing 2024 (quotes ke saath)\n4. Search: site:youtube.com GoHighLevel tutorial\n5. Images mein: GHL dashboard screenshot\n6. News mein: GoHighLevel latest update\n7. translate.google.com pe English text Urdu mein karo\n8. Google pe: 'GoHighLevel vs HubSpot'\n9. ChatGPT mein: 'Google advanced search tips'\n10. Jo bhi interesting mile — bookmark karo",
        "example": "Ahmed ko client ne kaha bakery ki GHL funnel banana hai. Google pe search kiya 'bakery GHL funnel example' — 5 minute mein real examples. Phir 'GHL bakery template' — free templates. Client: 'How do you know all this?' — sirf Google se!",
        "task": "Research Challenge karo:\n1. Google: 'GoHighLevel case studies' — 2 parho\n2. Google: 'Pakistan mein GHL freelancer income'\n3. YouTube: 'GoHighLevel complete tutorial 2024' — 10 min dekho\n4. Google: 'GHL alternatives' — list banao\n5. ChatGPT: 'GHL seekhne ka best roadmap beginners ke liye'\n\nSab ek Google Doc mein note karo:\n- 3 interesting cheezein\n- 1 surprising cheez\n- Apna 6-month plan",
        "submit_guide": "2 screenshots + 1 URL:\n- Screenshot 1: Google search results\n- Screenshot 2: Google Doc with notes\n- URL: Google Doc link",
        "success_criteria": "Research done, notes in Doc, 6-month plan written",
        "points": 40,
        "submission_type": "screenshot_and_url",
        "feedback_prompt": "Research skills ka feedback. Notes specific feedback do. 6-month plan realistic hai? Research being a core skill — emphasize karo."
    },
    {
        "day": 4,
        "title": "Professional Gmail Setup",
        "concept": "Email aaj bhi business communication ka backbone hai. Professional email rules:\n1. Clear subject line\n2. Short body\n3. Professional closing\n4. Email signature — naam, title, contact\n\nGmail features:\n- Labels/Folders\n- Filters — auto sorting\n- Templates\n- Scheduled send\n- Undo send (30 seconds)\n- Signature",
        "how_to": "1. gmail.com kholo\n2. Settings > See all settings\n3. General > Undo send: 30 seconds set karo\n4. Signature create karo:\n   [Naam]\n   GHL & Automation Specialist\n   📱 [Phone]\n   🌐 [Portfolio — baad mein]\n5. 'Clients' aur 'Learning' labels banao\n6. Template enable karo: Settings > Advanced > Templates\n7. Welcome template banao: 'Thank you for reaching out. I'll reply within 24 hours.'\n8. Test email bhejo ustaad.earn4pk@gmail.com pe",
        "example": "Sana ka client ne kaha 'Your email looks very professional' — sirf signature ki wajah se $300 project mila. Professional signature = professional perception.",
        "task": "1. Gmail signature banao (professional format)\n2. 'Clients' aur 'Learning' labels banao\n3. Undo send 30 seconds set karo\n4. Welcome template banao\n5. USTAAD ko email bhejo:\n   To: ustaad.earn4pk@gmail.com\n   Subject: 'Day 4 — Email Setup Complete'\n   Body: naam, kya setup kiya, ek seekhi hui cheez\n   Signature use karo\n6. Screenshots lo",
        "submit_guide": "2 screenshots:\n- Screenshot 1: Gmail settings mein signature\n- Screenshot 2: Sent email with signature visible",
        "success_criteria": "Professional signature, labels created, email sent",
        "points": 40,
        "submission_type": "screenshot",
        "feedback_prompt": "Signature professional hai? Email properly formatted? Email writing ke 2 tips share karo. Professional communication = client trust."
    },
    {
        "day": 5,
        "title": "Domain — Tumhari Online Identity",
        "concept": "Domain naam tumhara online address hai.\n\nDomain kaise kaam karta hai:\n- Browser mein 'google.com' type karo\n- DNS server se IP address milta hai\n- Browser connect karta hai\n\nDomain parts:\n- www = subdomain\n- google = naam\n- .com = TLD\n\nTLD types: .com (sabse popular), .pk, .org, .net, .io\nPrice: $10-15/year\nBest provider: Namecheap.com",
        "how_to": "1. namecheap.com kholo\n2. Apna naam + 'ghl' search karo (e.g. ahmedghl.com)\n3. Available options dekho\n4. Prices compare karo — .com vs .pk\n5. GoDaddy.com pe bhi compare karo\n6. ChatGPT: 'Domain best practices for GHL freelancers'\n7. Google: 'Best domain name for GHL agency'\n8. 3 domain ideas note karo apne business ke liye\n9. Renewal prices bhi note karo\n10. Business naam decide karo",
        "example": "Hassan ka domain 'hassanautomation.com' — sirf $12. Clients website dekh ke trust karte hain. $500 project sirf isliye mila kyunki 'You have a professional website.'",
        "task": "1. Namecheap pe 3 domain options search karo:\n   - [naam]ghl.com\n   - [naam]automation.com\n   - [sheher]ghl.com\n   Prices note karo\n2. ChatGPT: 'GHL agency naam suggest karo — Pakistan se hun, US clients chahiye' — 5 suggestions\n3. Google: 'Famous GHL agencies names' — inspiration\n4. Final decision: Apna business naam choose karo\n5. Google Doc mein: naam, domain, aur kyun choose kiya",
        "submit_guide": "2 screenshots:\n- Screenshot 1: Namecheap domain search results\n- Screenshot 2: Google Doc with chosen name and reasoning",
        "success_criteria": "3 domains researched, business name finalized, reasoning clear",
        "points": 40,
        "submission_type": "screenshot",
        "feedback_prompt": "Chosen naam evaluate karo — catchy, memorable, professional? Improvements suggest karo. Domain buying practical tips share karo."
    },
    {
        "day": 6,
        "title": "Hosting — Website ka Ghar",
        "concept": "Hosting wo service hai jo website ko internet pe 24/7 available rakhti hai.\nDomain = address, Hosting = makaan\n\nHosting types:\n1. Shared: $3-10/month (beginner)\n2. VPS: $20-50/month (medium)\n3. Dedicated: $100+/month (enterprise)\n4. Cloud: Scalable\n\nBest providers:\n- Hostinger: $3/month (beginner best)\n- SiteGround: $10/month (reliable)\n- Cloudways: $15/month (agencies)\n- DigitalOcean: $6/month (dev friendly)",
        "how_to": "1. hostinger.com kholo — plans compare karo\n2. siteground.com kholo — compare\n3. cloudways.com — pricing dekho\n4. Google: 'Hostinger vs SiteGround 2024'\n5. YouTube: 'Best hosting for WordPress beginners'\n6. ChatGPT: 'GHL agency ke liye best hosting aur kyun?'\n7. Hostinger checkout dekho — payment options\n8. Research: Pakistan se international payment methods (Wise, Payoneer)\n9. Google Sheets mein comparison table banao",
        "example": "Bilal ne Cloudways use kiya — $50/month mein 10 clients ki websites. Unse $30/month per website leta hai. Net: $250/month sirf hosting reselling se.",
        "task": "Google Sheets mein comparison table banao:\nColumns: Provider | Price/month | Storage | Speed | Pakistan payment\nRows: Hostinger, SiteGround, Cloudways, DigitalOcean\n\nHar site visit karo — data fill karo\nChatGPT: 'Pakistan se international hosting payment methods'\nPayoneer aur Wise research karo\nApna recommendation likho: kaunsi aur kyun",
        "submit_guide": "2 screenshots:\n- Screenshot 1: Google Sheets comparison table (filled)\n- Screenshot 2: Your recommendation text",
        "success_criteria": "Comparison table complete, recommendation with reasoning, payment methods researched",
        "points": 40,
        "submission_type": "screenshot",
        "feedback_prompt": "Table accuracy check karo. Recommendation sahi hai? Payoneer/Wise ke baare mein extra info do."
    },
    {
        "day": 7,
        "title": "DNS — Internet ka Directory",
        "concept": "DNS (Domain Name System) internet ka phone book hai.\n\nDNS Records:\n- A Record: Domain → IP address\n- CNAME: Domain → another domain\n- MX Record: Email routing\n- TXT Record: Verification\n- NS Record: Nameservers\n\nGHL use cases:\n- Client domain GHL pe point karna = A Record\n- Email setup = MX Records\n- Domain verify = TXT Record\n- Subdomain = CNAME\n\nPropagation: 24-48 hours lagti hai worldwide spread hone mein.",
        "how_to": "1. ChatGPT: 'DNS records explain with real GHL examples'\n2. dnschecker.org kholo\n3. google.com — A record check karo\n4. gmail.com — MX record check karo\n5. YouTube: 'How to change DNS for GHL' — 5 min video\n6. ChatGPT: 'Client ka domain GoDaddy pe hai, GHL pe point karna hai — steps'\n7. cloudflare.com kholo — free DNS management explore karo\n8. Note karo: DNS change karne ke steps",
        "example": "Zara ne client ka domain GoDaddy se GHL pe point kiya — sirf DNS settings change. 24 hours mein complete. Client ne $200 diye sirf is kaam ke liye.",
        "task": "1. dnschecker.org pe check karo:\n   - gohighlevel.com (A record, MX)\n   - gmail.com (MX)\n   - facebook.com (A record)\n   Records note karo\n2. ChatGPT scenario:\n   'Client domain: clientbusiness.com on GoDaddy. GHL website + Google Workspace email chahiye. Step by step DNS changes'\n   Answer Google Doc mein note karo\n3. Cloudflare.com research — kyun use karte hain?\n4. Summary likho: DNS kya hai, kyun zaroori, freelancer ke liye kaise use",
        "submit_guide": "2 screenshots:\n- Screenshot 1: dnschecker.org results\n- Screenshot 2: Google Doc with steps and summary (5+ lines in own words)",
        "success_criteria": "DNS records identified, step-by-step noted, own summary written",
        "points": 50,
        "submission_type": "screenshot",
        "feedback_prompt": "Concepts clear hain? DNS troubleshooting scenario do. Real-world DNS value explain karo."
    },
    {
        "day": 8,
        "title": "SSL Certificate — Website ki Security",
        "concept": "SSL encrypted connection banata hai. 🔒 = secure.\n\nhttps vs http:\n- http = insecure\n- https = SSL encrypted\n\nSSL kyun:\n1. Google HTTPS prefer karta hai\n2. Visitors trust karte hain\n3. Chrome: HTTP = 'Not Secure'\n4. Payments ke liye mandatory\n\nFree SSL:\n- Let's Encrypt\n- Cloudflare\n- Hosting companies\n\nGHL mein SSL automatic hai custom domains pe.",
        "how_to": "1. Chrome mein koi site kholo — 🔒 click karo\n2. 'Certificate is valid' click karo — details dekho\n3. http://example.com type karo — kya hota hai?\n4. ChatGPT: 'GHL custom domain pe SSL kaise set karein'\n5. ssllabs.com/ssltest pe popular site test karo\n6. Cloudflare.com — free account banao\n7. Note karo: SSL na ho toh kya masle",
        "example": "Ali ne client ke liye GHL funnel banaya. SSL activate nahi tha — browser warning. Cloudflare se free SSL lagaya — 10 minute. Client: '5 stars — professional work.'",
        "task": "1. 5 websites check karo SSL status:\n   - gohighlevel.com, namecheap.com, fiverr.com\n   - Ek Pakistani website, ek news site\n2. Certificate details dekho — konsi company ne issue kiya\n3. ChatGPT: 'GHL website pe SSL error — troubleshoot kaise karein'\n4. Cloudflare free account banao — explore karo\n5. Google Doc: SSL kya hai, kab zaroori, free options, GHL mein kaise",
        "submit_guide": "2 screenshots:\n- Screenshot 1: SSL certificate details\n- Screenshot 2: Cloudflare dashboard ya Google Doc summary",
        "success_criteria": "5 websites checked, Cloudflare explored, summary written",
        "points": 40,
        "submission_type": "screenshot",
        "feedback_prompt": "SSL understanding check. Practical scenario do. SEO benefits explain karo."
    },
    {
        "day": 9,
        "title": "WordPress — World ki Popular Website Builder",
        "concept": "WordPress 40% websites power karta hai.\n\nWordPress.org vs .com:\n- .org: Free software, apni hosting, full control\n- .com: Hosted service, limited\n\nStructure:\n- Dashboard: Admin panel\n- Posts: Blog articles\n- Pages: Static (Home, About)\n- Plugins: Extra features\n- Themes: Design\n- Users: Team\n- Settings: Config\n\nGHL + WordPress:\n- Clients WordPress sites rakhte hain\n- GHL forms embed hote hain\n- Tracking pixel lagta hai",
        "how_to": "1. wordpress.com — free account banao\n2. Blog/Business select karo\n3. Free domain: yourname.wordpress.com\n4. Dashboard explore karo\n5. Pages > Add New > 'About Me' page\n6. Title: About Me, apna introduction\n7. Publish karo\n8. Appearance > Themes > ek aur theme try karo\n9. Settings > General > title aur tagline\n10. ChatGPT: 'WordPress dashboard complete overview'",
        "example": "Farrukh ne WordPress login kiya, Elementor se GHL form embed kiya — 20 minute, $150 charged. WordPress knowledge directly paid kaam.",
        "task": "1. WordPress.com free site setup:\n   - Title: [Naam] — GHL Expert\n   - Tagline: GoHighLevel & Automation Specialist\n   - 2 pages: Home aur Services\n2. Services page:\n   - GHL Sub-Account Setup — $200\n   - Marketing Automation — $300/month\n   - GHL Training — $150\n3. Professional theme choose karo\n4. ChatGPT: 'WordPress pe GHL form kaise embed karein'\n5. Site link share karo",
        "submit_guide": "2 screenshots + 1 URL:\n- Screenshot 1: WordPress dashboard\n- Screenshot 2: Services page (published)\n- URL: WordPress site link",
        "success_criteria": "Site live, 2 pages, services listed, professional theme",
        "points": 50,
        "submission_type": "screenshot_and_url",
        "feedback_prompt": "Site visit karo. Design feedback, content feedback. WordPress advanced tip share karo. Portfolio foundation hai."
    },
    {
        "day": 10,
        "title": "HTML & CSS — Web ki Zabaan",
        "concept": "HTML aur CSS web ki language hai. GHL mein use hoti hai:\n- Email templates\n- Funnel styling\n- Custom code blocks\n- Tracking pixels\n- Form styling\n\nBasic HTML:\n<h1>Heading</h1>\n<p>Paragraph</p>\n<a href='url'>Link</a>\n<img src='img.jpg'>\n\nBasic CSS:\nh1 { color: blue; }\np { font-size: 16px; }",
        "how_to": "1. codepen.io kholo — free account\n2. 'New Pen' click karo\n3. HTML section mein:\n   <h1>Main GHL Expert Hun</h1>\n   <p>Pakistan se hun.</p>\n   <a href='https://gohighlevel.com'>GHL</a>\n4. CSS section mein:\n   h1 { color: #2563eb; }\n   p { color: #333; }\n5. Result dekho\n6. Colors experiment karo\n7. ChatGPT: 'GHL email mein custom HTML kaise'\n8. 5 important HTML tags note karo",
        "example": "Nadia ne GHL email mein logo center karna tha. ChatGPT se code mila: <center><img src='logo.jpg'></center>. Paste kiya — done. $50 extra tip.",
        "task": "CodePen pe professional intro page banao:\n\nHTML:\n- h1: Tumhara naam\n- h2: 'GHL Expert | Pakistan'\n- p: Bio (3-4 lines)\n- ul/li: Services list\n- a: Email link\n\nCSS:\n- Background: #f8f9fa\n- Heading color: professional\n- Font: Arial\n- Padding: 20px\n\nChatGPT se improvements karo. Link share karo.",
        "submit_guide": "1 screenshot + 1 URL:\n- Screenshot: CodePen editor + output\n- URL: CodePen link",
        "success_criteria": "HTML/CSS working, all elements, professional output",
        "points": 50,
        "submission_type": "screenshot_and_url",
        "feedback_prompt": "CodePen visit karo. Code aur output feedback. CSS improvement suggest karo. ChatGPT se HTML help lena OK hai."
    },
    {
        "day": 11,
        "title": "Google Drive — Professional File Management",
        "concept": "Cloud storage = files internet pe. Freelancer ke liye zaroori:\n- Client files organize\n- Proposals share\n- Reports bhejo\n- Team collaboration\n\nFolder Structure:\n📁 CLIENTS\n   📁 [Client Name]\n      📁 Contracts\n      📁 Invoices\n      📁 Work Files\n📁 TEMPLATES\n   📁 Proposals\n   📁 Invoices\n📁 LEARNING",
        "how_to": "1. drive.google.com\n2. Upar wali structure banao\n3. Google Doc: 'Proposal Template' — sections only\n4. Google Sheet: 'Invoice Template' — columns\n5. Share settings explore karo\n6. ChatGPT: 'GHL freelancer file organization system'\n7. File upload karo aur share link banao",
        "example": "Usman ka client ne 6 mahine purani invoice maangi. 30 seconds mein Drive se dhundhi aur bheji. Client: 'You're very organized.' — agle project direct call.",
        "task": "1. Complete folder structure banao\n2. 'My GHL Business' Google Doc banao TEMPLATES mein:\n   - My Services (with prices)\n   - My Process\n   - My Tools\n   - Contact Info\n3. Client Tracking Sheet banao:\n   Columns: Name | Project | Start | End | Amount | Status | Notes\n4. Fake client data add karo\n5. Doc shareable link banao\n6. Link share karo",
        "submit_guide": "2 screenshots + 1 URL:\n- Screenshot 1: Drive folder structure\n- Screenshot 2: Tracking sheet with data\n- URL: Shareable doc link",
        "success_criteria": "Complete structure, tracking sheet, shareable doc",
        "points": 50,
        "submission_type": "screenshot_and_url",
        "feedback_prompt": "Organization feedback. Advanced tip do (color-coded folders). Doc content review."
    },
    {
        "day": 12,
        "title": "Lead Generation — Clients Kahan Se Aate Hain",
        "concept": "Lead = potential customer. Lead sources:\n1. Upwork/Fiverr\n2. LinkedIn\n3. Facebook Groups\n4. Cold Outreach\n5. Referrals\n6. Content Marketing\n7. YouTube\n\nLead Funnel:\nStranger → Lead → Prospect → Client → Repeat\n\nGHL mein Lead Management:\n- Contacts mein add\n- Pipeline mein track\n- Follow up automate",
        "how_to": "1. ChatGPT: 'GHL freelancer top 5 lead gen strategies 2024'\n2. LinkedIn: 'GoHighLevel' search — kitne professionals\n3. Facebook: 'GoHighLevel users group' — 2-3 join karo\n4. Upwork: 'GoHighLevel' — jobs aur rates\n5. Fiverr: 'GoHighLevel expert' — top sellers\n6. Google: 'GHL freelancer success stories'\n7. YouTube: 'How I got my first GHL client'\n8. 3 best strategies note karo aur kyun",
        "example": "Hina ne Facebook GHL group join kiya. Roz helpful comments karti thi. 2 hafte mein DM aaya: 'You're knowledgeable, help me?' $400 project — zero paid ads.",
        "task": "1. Upwork 'GoHighLevel' search:\n   - Top 5 jobs note karo\n   - Average rate\n   - Skills required\n2. Fiverr 'GoHighLevel':\n   - Top 3 sellers profile\n   - Pricing aur reviews\n3. LinkedIn 'GoHighLevel specialist' — 3 profiles\n   - Headline, services\n4. Google Doc: Lead Generation Plan:\n   - 3 platforms\n   - First 30 days plan\n   - 3-month target\n5. Facebook pe GHL group join karo",
        "submit_guide": "2 screenshots:\n- Screenshot 1: Upwork ya Fiverr results\n- Screenshot 2: Lead Generation Plan Doc",
        "success_criteria": "Research done, realistic plan, group joined",
        "points": 50,
        "submission_type": "screenshot",
        "feedback_prompt": "Plan realistic hai? Best platform recommend karo aur kyun. Pehla client sabse mushkil — encourage karo."
    },
    {
        "day": 13,
        "title": "CRM — Customer Relationships Manage Karo",
        "concept": "CRM (Customer Relationship Management) clients ke saath sab interactions track karta hai.\n\nCRM ke bina:\n- Follow up miss\n- Deals slip\n- Unprofessional\n\nCRM mein:\n- Contacts: Leads aur clients\n- Deals: Active sales\n- Activities: Calls, emails log\n- Pipeline: Visual stages\n- Reports: Analytics\n\nGHL ek powerful CRM bhi hai.",
        "how_to": "1. hubspot.com — free CRM, account banao\n2. Dashboard: Contacts, Deals, Activities\n3. Fake contact add karo\n4. Deal add: 'GHL Setup Project' — $300\n5. Pipeline stages dekho\n6. ChatGPT: 'HubSpot vs GHL CRM differences'\n7. Google: 'GHL CRM features overview'\n8. Google Sheets CRM banao:\n   Columns: Name | Company | Email | Phone | Status | Last Contact | Next Action",
        "example": "Qasim ke 15 leads the, bina CRM ke confused. GHL CRM use kiya — pipeline, reminders. Pehle mahine 3 extra deals close huin. $900 extra. 'I almost forgot to follow up.'",
        "task": "1. HubSpot free CRM:\n   - 5 fake contacts (Pakistani business names)\n   - 3 deals different stages\n   - Pipeline: Inquiry → Demo → Proposal → Negotiation → Won/Lost\n2. Google Sheets simple CRM banao\n3. 5 fake entries\n4. ChatGPT: 'Simple CRM maintain karna as a freelancer'\n5. Note karo: Professional CRM kyun zaroori",
        "submit_guide": "2 screenshots:\n- Screenshot 1: HubSpot ya Sheets CRM with data\n- Screenshot 2: Pipeline view",
        "success_criteria": "CRM explored, contacts, pipeline stages",
        "points": 50,
        "submission_type": "screenshot",
        "feedback_prompt": "CRM setup feedback. Pipeline stages meaningful? GHL CRM yeh sab streamline karta hai — explain karo."
    },
    {
        "day": 14,
        "title": "Week 2 Review — Everything Connected",
        "concept": "2 haftoon mein tumne seekha:\nDay 8: SSL\nDay 9: WordPress\nDay 10: HTML/CSS\nDay 11: Google Drive\nDay 12: Lead Generation\nDay 13: CRM\n\nYeh sab ek project mein use hota hai:\nClient aata hai → WordPress site check (Day 9) → SSL verify (Day 8) → HTML customize (Day 10) → Drive mein track (Day 11) → Lead gen se mila tha (Day 12) → CRM mein manage (Day 13)",
        "how_to": "1. 7 dino ke tasks review karo\n2. ChatGPT: 'GHL freelancer typical day — step by step'\n3. Google: 'GHL freelancer portfolio examples'\n4. WordPress site update karo\n5. Drive folders review — improve karo\n6. HubSpot contacts update karo\n7. Reflection: Sabse zyada kya seekha?",
        "example": "Real scenario: Client emails — 'GHL setup chahiye real estate ke liye.'\n1. CRM mein add (Day 13)\n2. Proposal bhejo (Drive template — Day 11)\n3. Client site check — SSL? (Day 8)\n4. WordPress site dekho (Day 9)\n5. GHL connect — DNS changes (Day 7)\n6. Sub-account setup\n\nSab connected!",
        "task": "Mini-Project: 'Dr. Kamran Dental Clinic' Karachi:\n\n1. CRM (Sheets) mein client add karo — sab details\n2. Drive mein client folder: 'Dr. Kamran Dental'\n3. Proposal Google Doc:\n   - Title: GHL Setup Proposal\n   - Services: CRM, Appointments, Follow-up\n   - Price: PKR 35,000 / $125\n   - Timeline: 1 week\n4. WordPress Services page: dental services add\n5. ChatGPT: 'Dental clinic ke liye GHL setup mein kya include'\n6. 2-week summary: kya seekha, kya mushkil, aage kya",
        "submit_guide": "3 screenshots:\n- Screenshot 1: CRM entry\n- Screenshot 2: Proposal (first page)\n- Screenshot 3: 2-week summary",
        "success_criteria": "Complete mini-project, genuine reflection",
        "points": 60,
        "submission_type": "screenshot",
        "feedback_prompt": "Proposal quality check. CRM complete? Reflection genuine? Next 2 weeks preview do."
    },
    {
        "day": 15,
        "title": "LinkedIn — Professional Network",
        "concept": "LinkedIn professional social network hai.\n\nGHL freelancer ke liye:\n- US/UK clients directly\n- Professional credibility\n- Referrals\n- Job offers\n\nProfile parts:\n- Headline: 120 chars — sabse important\n- About: 3-5 paragraphs\n- Skills: GHL, CRM, Zapier\n- Featured: Best work\n\n❌ Bad: 'Freelancer | Learning GHL'\n✅ Good: 'GoHighLevel Expert | CRM & Marketing Automation | Pakistan'\n\nActivity: Post 3x/week, comment, connect",
        "how_to": "1. linkedin.com — account ya login\n2. Professional photo upload\n3. Headline: 'GoHighLevel & Automation Specialist | Pakistan 🇵🇰'\n4. About: ChatGPT se draft karo, personalize karo\n5. Skills: GoHighLevel, CRM, Zapier, Make.com, Lead Generation\n6. 10 GHL professionals connect karo\n7. Post karo: 'Main GHL seekh raha hun. Interesting cheez: [concept]. Tips?'",
        "example": "Imran ne LinkedIn optimize ki. 2 hafte posting ke baad UK company ka DM: 'Looking for GHL expert.' First client $500/month retainer — LinkedIn se, no ads.",
        "task": "1. Complete LinkedIn profile:\n   - Professional photo\n   - Optimized headline\n   - About section (ChatGPT draft + personalize)\n   - 5+ skills\n2. 10 GHL professionals connect\n3. Genuine post publish karo\n4. Profile URL share karo",
        "submit_guide": "2 screenshots + URL:\n- Screenshot 1: Profile with headline\n- Screenshot 2: Published post\n- URL: LinkedIn profile",
        "success_criteria": "Complete profile, post published, connections sent",
        "points": 50,
        "submission_type": "screenshot_and_url",
        "feedback_prompt": "Profile visit karo. Headline professional? About compelling? Post genuine? Specific improvements suggest karo."
    },
    {
        "day": 16,
        "title": "Funnel — Customer Journey ka Map",
        "concept": "Funnel marketing concept:\n1000 visitors → 100 signups → 10 buyers\n\nStages:\n1. Awareness (TOFU): Problem aware\n2. Consideration (MOFU): Solution dhundh rahe\n3. Decision (BOFU): Ready to buy\n\nFunnel types:\n- Lead Gen: Email collect\n- Sales: Sell\n- Webinar: Audience build\n\nFunnel vs Website:\n- Website: Multiple goals\n- Funnel: Single goal\n\nGHL funnels: Drag-drop, templates, analytics",
        "how_to": "1. ChatGPT: 'Real estate GHL lead gen funnel structure'\n2. Google Images: 'GHL funnel examples'\n3. YouTube: 'GoHighLevel funnel tutorial' — 10 min\n4. clickfunnels.com — examples dekho\n5. Google Slides mein funnel map banao:\n   Landing → Form → Thank You → Email sequence\n6. ChatGPT: 'Dental clinic ke liye best funnel'",
        "example": "Rabia ne dentist ke liye funnel:\n- Landing: 'Free Consultation'\n- Form: naam, phone, time\n- Thank you: appointment + WhatsApp\n- Workflow: SMS reminder\nResult: 40 leads, $500/month retainer.",
        "task": "Google Slides ya Canva pe funnel diagram:\nDental Clinic:\n- Page 1 (Landing): Headline, Benefits, Form\n- Page 2 (Thank You): Confirmed, next steps\n- Email 1: Welcome + details\n- Email 2: Clinic info\n- Email 3: Reminder\n\nHar stage ke liye: main message, CTA, goal\nChatGPT se improvements karo",
        "submit_guide": "2 screenshots:\n- Screenshot 1: Funnel diagram\n- Screenshot 2: ChatGPT feedback + improvements",
        "success_criteria": "Complete diagram, all stages, improvements applied",
        "points": 50,
        "submission_type": "screenshot",
        "feedback_prompt": "Funnel logical hai? Missing stages? GHL funnel extra features batao. Optimization tips share karo."
    },
    {
        "day": 17,
        "title": "Automation — Kaam Ko Autopilot Pe Lagao",
        "concept": "Automation: Ek baar setup, phir automatic.\n\nExamples:\n- Form submit → Email aaye\n- Deal won → Invoice generate\n- Appointment book → Reminder SMS\n\nTools:\n- GHL Workflows\n- Zapier\n- Make.com\n- n8n\n\nROI:\n- Setup: 2 hours\n- Saves: 10+ hours/month\n- Value: $200+/month\n\nGHL Workflow:\n- Trigger: Event\n- Actions: Tasks\n- Conditions: IF/ELSE\n- Wait: Delays",
        "how_to": "1. ChatGPT: 'Dental clinic ke liye GHL automations'\n2. zapier.com — free account, apps explore\n3. make.com — scenarios dekho\n4. YouTube: 'GHL workflow automation examples'\n5. Google Slides: Automation diagram\n6. 5 automation ideas note karo",
        "example": "Hassan ne gym automation:\n- Sign up → Welcome email + WhatsApp\n- Day 3 → Workout tips\n- Week 1 → Trainer call\n- Month 1 → Renewal reminder\n- No renewal → Win-back\nClient: 'I feel you're always there.' 30% retention improvement.",
        "task": "1. Zapier: Gmail → Google Sheets Zap try karo\n2. 3 businesses ke liye 5 automation ideas each:\n   a) Real Estate, b) E-commerce, c) Coaching\n3. ChatGPT: 'In businesses ke liye GHL automation best practices'\n4. Google Sheets: Automation Ideas Library\n   Columns: Business | Trigger | Actions | Result | Tool\n   10 rows fill karo",
        "submit_guide": "2 screenshots:\n- Screenshot 1: Zapier ya automation diagram\n- Screenshot 2: Automation Library (10 rows)",
        "success_criteria": "Automation concept clear, Zapier explored, 10-row library",
        "points": 50,
        "submission_type": "screenshot",
        "feedback_prompt": "Library ideas valuable? Zapier feedback. 2 best ideas highlight. GHL vs Zapier differences explain karo."
    },
    {
        "day": 18,
        "title": "Upwork aur Fiverr — Kahan Se Kaam Milta Hai",
        "concept": "Top platforms:\n\n1. Upwork:\n   - Hourly + fixed\n   - Professional clients\n   - 20% → 10% fee\n\n2. Fiverr:\n   - Gig-based\n   - Clients search karte hain\n   - 20% fee\n\n3. LinkedIn: No fee, premium clients\n4. Facebook Groups: Free\n\nStrategy:\n- Start Fiverr (easier reviews)\n- Move Upwork (better clients)\n- LinkedIn (premium)\n\nPakistani advantage: Lower starting rates, build reviews fast",
        "how_to": "1. Upwork.com — account banao\n2. 'GoHighLevel' search — jobs dekho, rates note karo\n3. Top profiles dekho — kya hain?\n4. Fiverr.com — 'GoHighLevel' search\n5. Top sellers gigs: pricing, packages, reviews\n6. Become a Seller explore\n7. PeoplePerHour.com — compare\n8. ChatGPT: 'Pakistan se Upwork GHL profile optimize tips'",
        "example": "Samina ne 3 Fiverr gigs:\n- GHL Setup: $50/$150/$300\n- Workflow: $75\n- Training: $40\n2 mahine: 5 orders, reviews. Phir $150 orders. 6 mahine: Level 1 Seller. Monthly $400-600.",
        "task": "1. Upwork profile banao:\n   - Title: 'GoHighLevel Expert | CRM & Automation'\n   - Overview: 300+ words\n   - Rate: $15-20\n   - Skills: GoHighLevel, Zapier, CRM\n2. Fiverr gig:\n   - 'I will set up your GoHighLevel sub-account'\n   - Basic $50, Standard $150, Premium $300\n   - 500+ word description\n3. Dono links share karo",
        "submit_guide": "3 screenshots + 2 URLs:\n- Upwork profile, Fiverr profile, Fiverr gig\n- Upwork URL, Fiverr gig URL",
        "success_criteria": "Both profiles complete, gig published",
        "points": 60,
        "submission_type": "screenshot_and_url",
        "feedback_prompt": "Profiles visit karo. Overview compelling? Gig description clear? Pehla review pane ke tips. Starting rates realistic."
    },
    {
        "day": 19,
        "title": "Proposal Writing — Clients Ko Convince Karo",
        "concept": "Winning Proposal Formula:\n1. HOOK: Client ki specific problem\n2. UNDERSTANDING: Pain point articulate\n3. SOLUTION: Specifically kya karoge\n4. PROOF: Past results\n5. TIMELINE: Delivery date\n6. PRICE: Clear breakdown\n7. CTA: Next step\n\nDON'Ts:\n- Generic copy-paste\n- 'Dear Sir/Madam'\n- Too long (300 words max)\n- No client research\n- Vague pricing",
        "how_to": "1. ChatGPT: 'Write winning Upwork proposal for GHL setup'\n2. Structure analyze karo\n3. Customize — personalize karo\n4. 3 scenarios practice:\n   a) Restaurant GHL\n   b) Real estate automation\n   c) Gym membership\n5. Each 200-250 words\n6. ChatGPT se review karwao",
        "example": "Farhan: 'I saw your post about losing track of leads. I've set up GHL for 2 real estate agencies — both saw 40%+ improvement. Here's exactly what I'd do...'\nClient: 'When can we start?' Project: $350.\n\nvs Generic: 'Dear Sir, I am expert.' Response: Crickets.",
        "task": "3 fake job posts ke proposals:\n\n1. 'Need GHL for dental clinic. 50 patients/month.'\n2. 'GHL for real estate leads. Budget $200.'\n3. 'GHL automation for coaching business.'\n\nHar proposal: 200-250 words, formula follow\nChatGPT review + improvements\nBest proposal choose karo + explain kyun\nGoogle Doc: 'My Proposal Templates'",
        "submit_guide": "2 screenshots:\n- Screenshot 1: 3 proposals in Doc\n- Screenshot 2: ChatGPT feedback + improvements",
        "success_criteria": "3 personalized proposals, feedback applied, best justified",
        "points": 60,
        "submission_type": "screenshot",
        "feedback_prompt": "Teeno proposals evaluate karo. Best proposal agree/disagree with reason. Most important improvement per proposal. Real acceptance probability batao."
    },
    {
        "day": 20,
        "title": "Pricing Strategy — Apni Value Pehchano",
        "concept": "Pricing models:\n1. Hourly: $15-35 starting\n2. Project: $150-500 per setup\n3. Retainer: $200-800/month\n4. Value-based: Most profitable\n\nPakistani freelancer journey:\nPhase 1 (0-3 months): Portfolio build\n  Setup: $100-200\nPhase 2 (3-6 months): Reviews\n  Setup: $200-350\nPhase 3 (6+ months): Premium\n  Setup: $350-600\n\nNever do FREE work.",
        "how_to": "1. Upwork: 'GoHighLevel' — rates filter karke dekho\n2. Fiverr: Pricing structure analyze\n3. ChatGPT: 'GoHighLevel freelancer pricing guide 2024'\n4. Google: 'GHL agency pricing packages'\n5. Calculate: $500/month target → average project $200 → 3 clients\n6. Apni price list banao",
        "example": "Raza: $30 → reviews → $100 → $200 → $350 → $500. 1 saal mein 10x. Reviews strong hain toh clients milte hain.",
        "task": "Complete GHL price list Google Doc:\n\nSETUP SERVICES: (PKR + USD)\n- Sub-Account Setup\n- CRM Config\n- Funnel Setup\n\nAUTOMATION:\n- Basic Workflow\n- Advanced Package\n- Zapier/Make Integration\n\nRETAINER:\n- Basic Management\n- Full Management\n\nTRAINING:\n- 1-hour, 5-hour package\n\nReasoning likho. ChatGPT se evaluate karwao. Profiles update karo.",
        "submit_guide": "2 screenshots:\n- Screenshot 1: Price list Doc\n- Screenshot 2: Updated profile prices",
        "success_criteria": "Complete list, reasoning, profiles updated",
        "points": 50,
        "submission_type": "screenshot",
        "feedback_prompt": "Prices realistic? Underpriced/overpriced kya hai? Value-based pricing example. Long-term strategy."
    },
    {
        "day": 21,
        "title": "Week 3 Review — Business Skills Check",
        "concept": "Week 3 complete:\nDay 15: LinkedIn\nDay 16: Funnel\nDay 17: Automation\nDay 18: Platforms\nDay 19: Proposals\nDay 20: Pricing\n\nAb tumhare paas:\n✓ LinkedIn professional\n✓ Fiverr + Upwork\n✓ Proposal templates\n✓ Price list\n✓ Funnel knowledge\n✓ Automation understanding\n\nMissing: Actual GHL — aagele course mein!",
        "how_to": "1. LinkedIn fresh eyes se dekho\n2. Fiverr gig review\n3. Upwork profile review\n4. Drive templates organized?\n5. Price list final?\n6. ChatGPT: 'GHL freelancer complete online presence checklist'\n7. Checklist ke against status\n8. Missing items fill karo",
        "example": "3-week journey:\nWeek 1: Technical foundation\nWeek 2: Web aur business\nWeek 3: Platforms aur sales\n\nResult: Complete freelance business setup!",
        "task": "'My GHL Freelance Business Checklist' Google Doc:\n\nONLINE PRESENCE:\n☐ LinkedIn complete\n☐ Upwork profile\n☐ Fiverr gig\n☐ WordPress site\n\nBUSINESS TOOLS:\n☐ Professional Gmail\n☐ Drive organized\n☐ Price list\n☐ Proposal templates\n☐ CRM setup\n\nHar item: Done/In Progress/Not Done\nNot Done items aaj complete karo\n\nFinal reflection (10+ lines): Kya seekha, kya mushkil, aage kya, 6-month goal\nBest work ka screenshot",
        "submit_guide": "3 screenshots:\n- Screenshot 1: Checklist with statuses\n- Screenshot 2: Reflection\n- Screenshot 3: Best work",
        "success_criteria": "Checklist complete, genuine reflection, best work highlighted",
        "points": 70,
        "submission_type": "screenshot",
        "feedback_prompt": "Checklist honestly filled? Reflection goals realistic? Best work genuine pride? GHL course preview do."
    },
    {
        "day": 22,
        "title": "Professional Communication Templates",
        "concept": "Professional communication rules:\n1. Subject: Clear aur specific\n2. Greeting: 'Hi [Name],' not 'Dear Sir'\n3. First line: Value ya context\n4. Body: Short, bullet points\n5. CTA: One clear action\n6. Sign-off: 'Best, [Name]'\n\nResponse time:\n- Same day: Professional\n- 1 hour: Exceptional\n- Next day: Acceptable\n- 2+ days: Lose clients",
        "how_to": "1. ChatGPT: '5 email templates for GHL freelancers'\n2. Templates customize karo\n3. Role play: ChatGPT ko demanding client banao\n4. Practice: Follow-up, revision, completion\n5. Drive mein templates folder",
        "example": "Client: 'Your work is not what I expected.'\nBad: 'Problem is from your side.'\nProfessional: 'I understand. Can we do a 15-min call? I want to get this exactly right. Available at [time1] or [time2]?'\nSame issue — different outcome.",
        "task": "Google Drive: 'Communication Templates' folder\n7 templates banao:\na) Initial outreach\nb) Proposal follow-up\nc) Project kickoff\nd) Weekly update\ne) Revision handling\nf) Project completion + testimonial\ng) Upsell existing client\n\nHar template: Subject, greeting, body, CTA, sign-off\nBest template choose karo + explain",
        "submit_guide": "2 screenshots:\n- Screenshot 1: Templates folder with all 7\n- Screenshot 2: Best template expanded",
        "success_criteria": "7 professional templates, ChatGPT reviewed",
        "points": 50,
        "submission_type": "screenshot",
        "feedback_prompt": "Templates quality check. Subject lines compelling? CTAs clear? Professional communication = income directly. 3 golden rules share karo."
    },
    {
        "day": 23,
        "title": "Canva — Professional Visuals Without Design Skills",
        "concept": "Canva free design tool. GHL freelancer use cases:\n- Fiverr gig images\n- LinkedIn cover\n- Social media posts\n- Presentations\n- Invoice design\n- Email headers\n\n250,000+ free templates\nDrag and drop\nBrand Kit\nDownload: PNG, JPG, PDF",
        "how_to": "1. canva.com — account banao\n2. 'LinkedIn Banner' search — template choose\n3. Edit: naam, tagline, colors, fonts\n4. Download — LinkedIn upload\n5. 'Fiverr Gig Image' template\n6. GHL gig ke liye customize\n7. 'Invoice' template\n8. Brand Kit: colors aur font set",
        "example": "Ali ne Canva se Fiverr gig image banai — 30 min. Gig clicks 3x badhe. Design quality directly revenue affect karta hai.",
        "task": "3 designs banao Canva mein:\n\na) LinkedIn Banner (1584x396):\n   - Naam + tagline\n   - 3 skills\n   - Professional\n\nb) Fiverr Gig Image (1280x769):\n   - 'GoHighLevel Expert'\n   - Service desc\n\nc) Business Card:\n   - Naam, title, email, phone, LinkedIn\n\nLinkedIn pe upload\nFiverr pe upload\nAll screenshots",
        "submit_guide": "3 screenshots:\n- LinkedIn with banner\n- Fiverr with gig image\n- Business card in Canva",
        "success_criteria": "3 designs, uploaded, brand consistent",
        "points": 50,
        "submission_type": "screenshot",
        "feedback_prompt": "Designs actually visit karo. Honest quality feedback. Specific improvement. Advanced Canva tip."
    },
    {
        "day": 24,
        "title": "Time Management — Productive Rehna",
        "concept": "Freelancer time problems:\n- Procrastination\n- No clear hours\n- Client messages 24/7\n- Multiple projects\n- Burnout\n\nSystems:\n1. Pomodoro: 25 min work, 5 min break\n2. Time Blocking: 9-11 client, 11-12 proposals\n3. Eisenhower Matrix: Urgent+Important = Do Now\n\nTools: Google Calendar, Todoist, Toggl\n\nGolden Rule: Client hours set karo — '9am-6pm PKT'",
        "how_to": "1. Google Calendar: Next week time blocks\n2. Todoist.com: Tasks + priorities\n3. Toggl.com: Time tracking\n4. ChatGPT: 'Freelancer ideal schedule — Pakistan to US clients'\n5. Pomodoro session karo — 25 min focused kaam",
        "example": "Hamza time blocks:\n9am-12pm: Client work\n12-1pm: Proposals\n1-2pm: Lunch\n2-4pm: Learning\n4-6pm: Admin\nResult: Income 40% badhi — zyada client work fit hota hai.",
        "task": "1. Google Calendar: Next 7 days schedule:\n   - Learning blocks\n   - Practice blocks\n   - Outreach blocks\n   - Breaks\n2. Todoist: Next 3 days tasks + priorities\n3. Toggl: 'USTAAD Learning' project, aaj time track karo\n4. Availability Policy (Google Doc):\n   - Working hours\n   - Response time\n   - Contact method\n   - Do/don't do\n5. Pomodoro session karo",
        "submit_guide": "3 screenshots:\n- Google Calendar with blocks\n- Todoist task list\n- Availability Policy",
        "success_criteria": "Complete schedule, tasks with priorities, policy written",
        "points": 50,
        "submission_type": "screenshot",
        "feedback_prompt": "Schedule realistic? Learning + work balance? Personal time included? Burnout bachne ka key tip."
    },
    {
        "day": 25,
        "title": "Invoicing aur Payments",
        "concept": "Professional invoice zaroori hai.\n\nInvoice mein:\n- Invoice number (INV-001)\n- Date + due date\n- Your info\n- Client info\n- Services + amounts\n- Payment methods\n\nPayment methods Pakistan:\n1. Payoneer: Most popular\n2. Wise: Low fees\n3. PayPal: High fees\n4. Platform payments\n5. Crypto USDT\n\nFree tools: Wave.com, Invoice Ninja",
        "how_to": "1. wave.com — free accounting\n2. Business info setup\n3. Test invoice banao\n4. PDF download\n5. Payoneer.com — registration dekho\n6. ChatGPT: 'Pakistan international payment 2024'\n7. Tax basics research",
        "example": "Sara pehle WhatsApp pe maangti thi payment — ignored. Professional Wave invoices bhejne lagi. Payment time 30 days → 5 days. 'Professional invoice = professional client.'",
        "task": "1. Wave business setup\n2. 2 invoices:\n   - Dr. Kamran Dental: $200\n   - Ahmed Real Estate: $350\n3. PDFs download\n4. Payment Tracker Sheets:\n   Invoice# | Client | Amount | Sent | Due | Paid | Status\n5. Fake entries (overdue bhi)\n6. ChatGPT: 'Overdue invoice follow-up professional email'",
        "submit_guide": "3 screenshots:\n- Wave invoice\n- Payment tracker\n- Overdue email template",
        "success_criteria": "Wave setup, 2 invoices, tracker, template",
        "points": 50,
        "submission_type": "screenshot",
        "feedback_prompt": "Invoice professional? Tracker complete? Pakistan payment advice — Payoneer vs Wise. Tax basics."
    },
    {
        "day": 26,
        "title": "Personal Branding — Tum Ek Brand Ho",
        "concept": "Personal brand = Jab log tumhara naam sunein, kya sochain.\n\nElements:\n1. Niche: GHL for [specific industry]\n2. Tone: Friendly, expert, educator\n3. Visual: Consistent design\n4. Story: Relatable journey\n5. Content: Tips, results, behind-scenes\n\nContent pillars:\n- GHL tutorials\n- Automation hacks\n- Freelancing lessons\n- Client results\n\nBrand Statement:\n'I help [who] achieve [what] using [how]'",
        "how_to": "1. Niche decide karo: GHL for [industry]\n2. LinkedIn content calendar — 2 weeks\n3. Post mix: 2 educational, 1 personal, 1 results\n4. Ek post aaj publish\n5. ChatGPT: 'GHL LinkedIn content ideas — 10'\n6. Canva: Consistent post template\n7. Brand Statement finalize",
        "example": "Nida chose: 'GHL for restaurants'\nPosts: 'How restaurants lose 30% revenue...' + 'GHL setup results' + '5 automations every restaurant needs'\nResult: Restaurant owners following her. 3 DMs. All became clients. Niche = magnetic.",
        "task": "1. Brand Statement: 'I help [industry] businesses [achieve] using [GHL/automation]'\n2. LinkedIn:\n   - About update with brand statement\n   - Featured: best work\n   - Post: 'My GHL Learning Journey — Week 4'\n3. Content Calendar (Google Sheets, 30 days):\n   Date | Type | Topic | Platform | Status\n   12+ posts\n4. Canva post template\n5. Fiverr + Upwork profiles update",
        "submit_guide": "3 screenshots:\n- LinkedIn (About + brand statement)\n- Content calendar\n- Canva template",
        "success_criteria": "Clear brand statement, 12+ calendar posts, consistent design",
        "points": 60,
        "submission_type": "screenshot",
        "feedback_prompt": "Brand statement specific aur compelling? Calendar realistic? Niche advice — specialization wise hai? 2 impactful branding tips."
    },
    {
        "day": 27,
        "title": "Client Onboarding System",
        "concept": "Client onboarding: Naye client ko professionally welcome karna.\n\nWhy matters:\n- First impression\n- Clear expectations\n- Professional value\n\nSteps:\n1. Welcome email\n2. Onboarding form (business details, access, goals)\n3. Kickoff call (30 min)\n4. Project folder\n5. Contract/Agreement\n\nGHL onboarding:\n- Domain access\n- Current website\n- Business info\n- Sales process",
        "how_to": "1. ChatGPT: 'GHL freelancer client onboarding checklist'\n2. Google Forms: Onboarding questionnaire\n3. Questions: Business info, technical access, goals\n4. Welcome email template\n5. Kickoff call agenda\n6. Drive: Client Onboarding folder",
        "example": "Amir ka system: Automatic welcome email → Google Form → Kickoff call ready. Client: 'Most organized freelancer I've worked with.' Result: 5-star review + 2 referrals.",
        "task": "1. Google Forms: 'GHL Client Onboarding Form' (15+ questions):\n   - Personal/business (5)\n   - Technical access (5)\n   - Goals (5)\n2. Welcome email template\n3. Kickoff agenda (Google Doc):\n   - Intros, goals, deliverables, expectations, next steps, Q&A\n4. Client folder template in Drive\n5. Dr. Kamran fake onboarding: sab steps follow karo",
        "submit_guide": "3 screenshots:\n- Google Form (15+ questions)\n- Welcome email + kickoff agenda\n- Dr. Kamran fake onboarding done",
        "success_criteria": "15+ question form, templates ready, fake onboarding complete",
        "points": 60,
        "submission_type": "screenshot",
        "feedback_prompt": "Form comprehensive? Important questions missing? Welcome email professional? Smooth onboarding = referrals."
    },
    {
        "day": 28,
        "title": "AI Tools — Tumhara Secret Weapon",
        "concept": "AI tools 10x productivity:\n\n1. ChatGPT: Research, writing, strategy\n2. Claude: Long docs, complex writing\n3. Canva AI: Design\n4. Loom: Screen recording\n5. Otter.ai: Meeting transcription\n6. Notion AI: Notes\n\nGHL + AI:\n- GHL ka AI content writer\n- AI chatbots integrate\n- Lead qualification\n\nWarning: AI helps but GHL knowledge replace nahi karta.",
        "how_to": "1. claude.ai account banao\n2. ChatGPT: Dental clinic GHL strategy — comprehensive\n3. Claude: Same question — compare\n4. loom.com: Screen recording\n5. notion.so: Notes organize\n6. AI tools comparison table",
        "example": "Mehwish: 3 ghante email sequences likhti thi. ChatGPT brief diya → 10 min draft → 30 min edit = 40 min total. Client: 'Emails are excellent.' Same paise, zyada projects.",
        "task": "1. ChatGPT: Real estate + Islamabad + 20 leads GHL plan:\n   - Features, automations, funnel, email outline, report template\n2. Claude: Same question — compare\n3. Loom: 2 min screen recording of any tool\n4. Notion: 'GHL Learning Notes' — important concepts\n5. AI tools comparison table:\n   Tool | Free/Paid | Best For | GHL Use Case",
        "submit_guide": "3 screenshots:\n- ChatGPT comprehensive plan\n- Notion notes\n- AI comparison table\n(Loom link optional — bonus points)",
        "success_criteria": "AI tools explored, comprehensive plan, Notion setup, table",
        "points": 60,
        "submission_type": "screenshot",
        "feedback_prompt": "AI use effective? Output actionable? Notion organized? Advanced AI tips. Warning: AI + GHL knowledge dono chahiye."
    },
    {
        "day": 29,
        "title": "Complete Portfolio Package",
        "concept": "29 dino mein tumne seekha:\n✓ Computer + Internet\n✓ Domain, Hosting, DNS, SSL\n✓ WordPress, HTML/CSS\n✓ Google Drive\n✓ Lead Gen, CRM\n✓ LinkedIn, Platforms\n✓ Funnels, Automation\n✓ Proposals, Pricing\n✓ Communication\n✓ Canva\n✓ Time Management\n✓ Invoicing\n✓ Personal Branding\n✓ Onboarding\n✓ AI Tools\n\nAaj: Sab kuch ek jagah organize karo.",
        "how_to": "1. 29 dino ke tasks review\n2. Missing items identify\n3. Complete karo — last chance\n4. ChatGPT: 'GHL freelancer portfolio checklist'\n5. Gaps fill karo",
        "example": "Portfolio = Demo reel. Client: 'Kya experience hai?' — Portfolio dikhao. Organized professional portfolio strong first impression. 'You seem very prepared.' — clients yahi kehte hain.",
        "task": "Drive: 'PORTFOLIO' folder mein:\n\n1. PROFILES:\n   - LinkedIn URL\n   - Upwork URL\n   - Fiverr URL\n   - WordPress URL\n\n2. WORK SAMPLES:\n   - Dr. Kamran Dental — funnel plan PDF\n   - Ahmed Real Estate — proposal PDF\n   - Sara Beauty — automation diagram\n\n3. TEMPLATES:\n   - 3 proposals, 7 email templates\n   - Invoice template\n   - Onboarding form link\n\n4. BUSINESS DOCS:\n   - Price list, packages, availability, brand statement\n\n5. SKILLS PROOF:\n   - WordPress, CodePen, Drive, Canva screenshots\n\nMaster doc: 'My GHL Freelance Business' — sab links",
        "submit_guide": "2 screenshots + URLs:\n- Drive folder structure\n- Master overview doc\n- LinkedIn, Upwork, Fiverr, WordPress links",
        "success_criteria": "All portfolio components, organized, master doc complete",
        "points": 80,
        "submission_type": "screenshot_and_url",
        "feedback_prompt": "Portfolio job-ready? Genuine strengths highlight. 3 improvements before Day 30. GHL skills add hone ke baad 10x valuable hoga."
    },
    {
        "day": 30,
        "title": "GRADUATION DAY — Reflection aur Next Steps",
        "concept": "Mubarak ho! 30 days complete!\n\nAb tumhare paas:\n- Professional online presence\n- Business setup\n- Portfolio\n- Templates library\n- Skills foundation\n\nAage:\nPhase 2: Web Fundamentals (30 days) — PKR 5,000\nPhase 3: GHL Developer (45 days) — PKR 7,000\nPhase 4: Integration Expert (45 days) — PKR 8,000\nPhase 5: Client Hunting (45 days) — PKR 12,000\n\nExpected income:\n- 0-3 months: $300-500/month\n- 3-6 months: $700-1500/month\n- 6-12 months: $1500-3000/month\n- 1+ year: $3000-5000+",
        "how_to": "1. 30 din mentally review karo\n2. Har week se favorite learning note karo\n3. Biggest achievement identify karo\n4. GHL community join karo\n5. LinkedIn graduation post\n6. USTAAD ko genuine feedback email",
        "example": "Day 1: 'Mujhe kuch nahi aata.'\nDay 30: LinkedIn profile, Fiverr gig, Upwork profile, portfolio, price list, templates — sab ready.\n30 din mein yeh transformation possible hai.",
        "task": "'30-Day Journey Letter' Google Doc (20+ lines):\n- Day 1 vs Day 30\n- Sabse bada lesson\n- Challenging moment\n- Proud moment\n- Next phase plan\n- 6-month income goal\n- Commitment statement\n\nLinkedIn graduation post:\n'USTAAD Computer Basics complete! [3 achievements]. GHL seekhne ready. Connect karein!'\n\nPortfolio final review\nNext phase register ya plan\nUSTAAD feedback email",
        "submit_guide": "3 screenshots:\n- 30-day letter (first page)\n- LinkedIn graduation post\n- Final portfolio overview",
        "success_criteria": "Genuine reflection 20+ lines, LinkedIn post, portfolio complete, feedback sent",
        "points": 100,
        "submission_type": "screenshot",
        "feedback_prompt": "GRADUATION! Letter genuine? Growth real? LinkedIn post dekho. Heartfelt, specific feedback do. Achievements highlight karo. Next phase excitement create karo. 'Yeh sirf foundation hai — GHL ke baad real income start hogi.' Unhe genuinely proud feel karao."
    }
]


def get_day_curriculum(day: int) -> dict:
    if 1 <= day <= 30:
        return COMPUTER_BASICS_30_DAYS[day - 1]
    return {}


def get_week_curriculum(week: int) -> list:
    start = (week - 1) * 7
    end = start + 7
    return COMPUTER_BASICS_30_DAYS[start:end]
