import { create } from 'zustand'
import { persist } from 'zustand/middleware'

const translations = {
  en: {
    welcome: 'Welcome to USTAAD',
    tagline: 'Learn. Do. Earn.',
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    city: 'City',
    phone: 'Phone Number',
    dashboard: 'Dashboard',
    myTasks: 'My Tasks',
    chat: 'Chat',
    profile: 'Profile',
    todayTask: "Today's Task",
    streak: 'Day Streak',
    progress: 'Progress',
    submit: 'Submit',
    startTask: 'Start Task',
    uploadFile: 'Upload File',
    takePhoto: 'Take Photo',
    chooseGallery: 'Choose from Gallery',
    loading: 'Loading...',
    submitting: 'Submitting...',
    success: 'Success!',
    error: 'Something went wrong',
    pending: 'Pending Approval',
    pendingMsg: 'Your account is under review. Admin will approve shortly.',
    noTask: 'No task today. Rest well!',
    changeLanguage: 'Change Language',
    logout: 'Logout',
    score: 'Score',
    feedback: 'Feedback',
    nextTask: 'Next Task',
    points: 'Points',
    level: 'Level',
    completion: 'Completion',
    accuracy: 'Accuracy',
    effort: 'Effort',
    understanding: 'Understanding',
    consistency: 'Consistency',
  },
  ur_nastaliq: {
    welcome: 'USTAAD میں خوش آمدید',
    tagline: 'سیکھو۔ کرو۔ کماؤ۔',
    login: 'لاگ ان',
    signup: 'اکاؤنٹ بنائیں',
    email: 'ای میل',
    password: 'پاس ورڈ',
    fullName: 'پورا نام',
    city: 'شہر',
    phone: 'فون نمبر',
    dashboard: 'ڈیش بورڈ',
    myTasks: 'میرے کام',
    chat: 'چیٹ',
    profile: 'پروفائل',
    todayTask: 'آج کا کام',
    streak: 'دن کا سلسلہ',
    progress: 'پیش رفت',
    submit: 'جمع کریں',
    startTask: 'کام شروع کریں',
    uploadFile: 'فائل اپلوڈ کریں',
    takePhoto: 'تصویر لیں',
    chooseGallery: 'گیلری سے منتخب کریں',
    loading: 'لوڈ ہو رہا ہے...',
    submitting: 'جمع ہو رہا ہے...',
    success: 'کامیاب!',
    error: 'کچھ غلط ہوا',
    pending: 'منظوری زیر التواء',
    pendingMsg: 'آپ کا اکاؤنٹ زیر جائزہ ہے۔ ایڈمن جلد منظور کرے گا۔',
    noTask: 'آج کوئی کام نہیں۔ آرام کریں!',
    changeLanguage: 'زبان تبدیل کریں',
    logout: 'لاگ آؤٹ',
    score: 'اسکور',
    feedback: 'رائے',
    nextTask: 'اگلا کام',
    points: 'پوائنٹس',
    level: 'سطح',
    completion: 'تکمیل',
    accuracy: 'درستگی',
    effort: 'کوشش',
    understanding: 'سمجھ',
    consistency: 'تسلسل',
  },
  ur_roman: {
    welcome: 'USTAAD mein khush aamdeed',
    tagline: 'Seekho. Karo. Kamao.',
    login: 'Login karein',
    signup: 'Account banayein',
    email: 'Email',
    password: 'Password',
    fullName: 'Poora naam',
    city: 'Sheher',
    phone: 'Phone number',
    dashboard: 'Dashboard',
    myTasks: 'Mere kaam',
    chat: 'Chat',
    profile: 'Profile',
    todayTask: 'Aaj ka kaam',
    streak: 'Din ka silsila',
    progress: 'Taraqi',
    submit: 'Jama karein',
    startTask: 'Kaam shuru karein',
    uploadFile: 'File upload karein',
    takePhoto: 'Tasveer lein',
    chooseGallery: 'Gallery se chunein',
    loading: 'Load ho raha hai...',
    submitting: 'Jama ho raha hai...',
    success: 'Kamiyab!',
    error: 'Kuch ghalat hua',
    pending: 'Manzuri ka intezaar',
    pendingMsg: 'Aapka account review mein hai. Admin jald approve karega.',
    noTask: 'Aaj koi kaam nahi. Aaram karein!',
    changeLanguage: 'Zaban tabdeel karein',
    logout: 'Logout',
    score: 'Score',
    feedback: 'Feedback',
    nextTask: 'Agla kaam',
    points: 'Points',
    level: 'Level',
    completion: 'Mukammil',
    accuracy: 'Durusti',
    effort: 'Koshish',
    understanding: 'Samajh',
    consistency: 'Consistency',
  }
}

export const useLangStore = create(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language
        return translations[lang]?.[key] || translations.en[key] || key
      },
      isUrdu: () => get().language !== 'en',
      isRTL: () => get().language === 'ur_nastaliq',
    }),
    { name: 'ustaad-lang' }
  )
)
